language: node_js

node_js:
  - '6'

install:
  # install dependencies
  - set -e
  - npm install

script:
  # build and test
  - set -e
  - gulp test

deploy:
  provider: s3
  access_key_id:
    secure: "cJQQ+90RPUNBs8UoSu81lyf2e9YnbG32kaTvlvb2JGLGqwXHfYCd5hszFs045Gc8dxd+9RTm8ZBHrGRXp4xCzIvCRXJIaMW9G+9q9lJEKJN2r/84KQc7Uio/gMMFulifRFFzHbK/lOWadCZGadS+2TdIcmUrm8sAyZ+asekXGjgB7ZvX+7gqQZD/RFkx2FViRk5bSdxaoXlO2WX+heIK9pVkoW8mVsUcIQiIycbWdckU4qoCa6Cfme6qpY7D5Qs4zdFhocv9L3riSqCzB7ZCNq6Q5PtCsNMqy+0w0Rg78smbTLAdL3RK2lTi4kAVMZdubHIOoBn+oWZoJH4gIKdUL6ssbBEdJpdkJS1GveCxEllo+nVhfi73bb+sx6RcArV+6Gbq/unZEV+YkoIgl/BNh3lvx1pg4Hy1kX4po1PwSO22Nv1rvmg7C2d8eXmsN2AtjWtzpKGtr5bs33NvODY8soAEr75yoRZAWQWP1pl3j3ozJWHnzWynWPQ0W7SzyVMMKftVACWZDBH4Ap+du/LlT5F8sKK0w957Ua6KZrtDTOWh878gRBkMO/62VRfQKnYleW08pkFmRcd2+/hrCWikxdDCTpSPzwQ58an/Rg416RNdf2wnCLYyUkE+G48hgXL9eBGh3+rurcRiwXFpK8mc4e56n2GlCWT5WPtx7ijxyVI="
  secret_access_key:
    secure: "XR9cot/0mw18AhrKlyIVkpb7fBtNguLO72w9BZNVEvQJyiA796aQ3xkaQjMUUkMJlAY07eo+QpuhTxrRDj0HY/CILEhAW96DdU1wy5kGxtH4fDCFhAp96iFwNmStwAaDfas42Ouu+nY4ZpKb/370j26ku7wa7fhSAqY3YJd2u3c1+IAhR54YPUtW1awm+1tojvGU2KyNqqYPFtI208yD3bwmfmRHxgRnAZk58pa8KslS+tqh08/w7cp1Bjo+5yKK1Eoqh8/aiP3NcwFD4z676YCDUrBlDYJn2hApKceUn1sGuSZV01KZvBXc329ex3v3QX9ZCABAnZ2iNWmCs1U4LIQg+8MZYk04I/9zEu98D63qVEAYXataHnXzhy2xQlGnwzZp6IGg8foKrzD3aX7NTi4V2oCV0u43LZ0IJ+0dFlhD+PAK0jxcNk5ik+JzdWCY2oQauqnstPl3T6vN1PBnR/UiVIEIOTvk06kssRSIdQO3BNr3MvrOE2aeo6eoiQ/0W4Jofmj5ClbAmZbeCnKPX4h1vf3QxxKCW/cxn2lwmf5RlVEZyBvjdKfH5VucBX5NJ33tsweuCsw4V820u993TXQQhMHUOfHQQc8Qh4sm763AQ61D7muOvB1hXPdoxwFchUnMl9GCSrlilg3R2vhu9JAveghZLSNvRFoINTDrJrc="
  bucket: andrewmacheret.com
  skip_cleanup: true
  acl: public_read
  region: us-east-1
  default_text_charset: utf-8
  detect_encoding: true
  local_dir: build
  upload_dir: projects/raytracer
